### PR TITLE
tracer: update gobpf and set maxactive

### LINKED ISSUE #34: missing "accept" events in some scenario: kretprobe maxactive too low for accept()
The 'maxactive' attribute for kretprobes can be too low and cause kretprobes to be missed. This has caused offsetguess.go to sometimes fail on single-core VMs (bug https://github.com/weaveworks/scope/issues/2379, worked around successfully with #33).

But the 'maxactive' limitation can also cause problems after initialization and cause missing "accept" events, even on multi-cores. Reproduction steps (100% reproducible):
1. Start the tracer: `sudo ./tracer`
2. In another shell, start a bunch of processes waiting on the `accept()` system call: `for i in $(seq 1 25) ; do (busybox nc -l -p $((8081 + i)) &) ; done`
3. Start nginx locally: `sudo docker run -d nginx`
4. Connect to nginx: `curl 172.17.0.2`
5. Notice that the "accept" event is missing. The other events ("connect" and "close") are fine:
```
24932019863063 cpu#0 connect 10674 curl 172.17.0.1:33280 172.17.0.2:80 4026531969
24932020412145 cpu#0 close 10674 curl 172.17.0.1:33280 172.17.0.2:80 4026531969
24932020692600 cpu#2 close 9725 nginx 172.17.0.2:80 172.17.0.1:33280 4026532680
```
6. As soon as the busybox processes are terminated, the tracer works correctly again.

Note: use `nc` from `busybox` to reproduce this issue. `nc` from https://nmap.org/ncat (the default on Fedora) will not reproduce the issue because it does not block on the accept() system call (it waits on the `select()` system call to know when there is an incoming connection and only start the `accept()` system call at that time). I have not seen this issue on microservices-demo. This might be because it uses asynchronous sockets or because it does not have enough processes using `accept()` in a synchronous way to cause the problem.

/cc @schu @iaguis @2opremio

### PR DESCRIPTION
**Pull request by iaguis**
Gobpf gained support for configuring the 'maxactive' attribute for kretprobes.

This requires kernel support, which is not merged yet: https://lkml.org/lkml/2017/4/3/225

If the kernel doesn't have support for it, we'll fall back to the default, so things shouldn't change for that case.

Fixes #34

### CODE REVIEW

File: pkg/tracer/tracer.go [hunk 1]
```diff
@@ -16,6 +16,12 @@ type Tracer struct {
 	stopChan    chan struct{}
 }
 
+// maxActive configures the maximum number of instances of the probed functions
+// that can be handled imultaneously.
```
Comment (chrskhl) [inline pkg/tracer/tracer.go]: simultaneously.

**Review by alban — CHANGES_REQUESTED** [review]
The commit message could mention that we need to include the changes from 
https://github.com/iovisor/gobpf/pull/39
