### PR TITLE
tcptracer-bpf.c: remove dead entries from the tuplepid_ipv{4,6}

### LINKED ISSUE #21: "connect" events stop being generated after too many connection refused errors
In kprobe__tcp_set_state(), we don't do anything if the connection is not established. This is because we don't want to generate a "connect" event in case of errors (connection refused or connection timeout):
```
	if (state != TCP_ESTABLISHED) {
		return 0;
	}
```

But we don't clean up the maps tuplepid_ipv4 and tuplepid_ipv6. So the maps can get full and then we will not get any "connect" event anymore.

To reproduce the issue, start tcptracer-bpf (`cd tests ; sudo ./tracer` in a separate terminal) and generate a lot of connection refused (more than `max_entries = 1024`):
```bash
for i in $(seq 1 1200 ) ; do wget http://127.0.0.1:1234 ; done
```

Then, generate new connections:
```
wget www.google.com
```

The "close" events are still generated but not the "connect" events.

AFAIR, fixing this is not as easy as just removing the entry from tuplepid_ipv4 because tcp_set_state() might be called for some intermediary tcp states (e.g. `TCP_SYN_SENT`).

/cc @schu @alepuccetti

### PR DESCRIPTION
**Pull request by iaguis**
This patch avoids that `tuplepid_ipv{4,6}` fill up with dead entries
because a connection was refused.

Fixes #21

Depends on #25

### CODE REVIEW

**Comment by alban** [comment]
I tested this branch with half-duplex connections because the tcp connections goes to different states in the kernel in those cases (calling `tcp_set_state` differently).

Calling `shutdown(..., SHUT_WR)`  server-side:
```
echo foo | busybox nc -l -p 1234
busybox nc 127.0.0.1 1234
```

Calling `shutdown(..., SHUT_WR)` client-side:
```
busybox nc -l -p 1234
echo bar | busybox nc 127.0.0.1 1234
```

Note: I am using the busybox netcat. The GNU netcat or BSD netcat have a different implementation, they might not use `shutdown(2)` in the same way. It's best to check with "strace" that `shutdown(2)` is called according to the test scenario.

And it worked fine for me.

File: tcptracer-bpf.c [hunk 1]
```diff
@@ -538,6 +538,9 @@ int kprobe__tcp_set_state(struct pt_regs *ctx)
 		if (!read_ipv4_tuple(&t, status, skp)) {
 			return 0;
 		}
+		if (state == TCP_CLOSE) {
+			bpf_map_delete_elem(&tuplepid_ipv4, &t);
```
Comment (alban) [inline tcptracer-bpf.c:539]: Could you add `return 0;` after deleting the entry from the map? It'll make it more clear that it will not emit a dummy "connect" event with `bpf_perf_event_output` line 570 in that case. The current patch works because it relies on the test line 547-549 to do the `return 0;`... but it's less readable IMO.

Ditto for the IPv6 branch.

Comment (iaguis) [reply tcptracer-bpf.c:539]: Done

**Review by schu — APPROVED** [review]
LGTM
